CREATE DATABASE IF NOT EXISTS `puzzle_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `Image`; 
DROP TABLE IF EXISTS `lieu`; 
DROP TABLE IF EXISTS `Permission`; 
DROP TABLE IF EXISTS `Role`; 
DROP TABLE IF EXISTS `role_permission`; 
DROP TABLE IF EXISTS `role_utilisateur`; 
DROP TABLE IF EXISTS `Utilisateur`;
SET FOREIGN_KEY_CHECKS = 1;


-- Generated by Mocodo 4.3.2

CREATE TABLE Image (
  PRIMARY KEY (id_image),
  id_image       INT NOT NULL AUTO_INCREMENT,
  nom_image      VARCHAR(42),
  url            VARCHAR(42),
  id_utilisateur INT NULL,
  nom_monument   VARCHAR(42) NULL,
  description    VARCHAR(42) NULL,
  nom_commune    VARCHAR(42) NULL,
  geoloc         VARCHAR(42) NULL
);

CREATE TABLE Lieu (
  PRIMARY KEY (nom_commune),
  nom_commune VARCHAR(42) NOT NULL,
  code_dept   INT,
  nom_dept    VARCHAR(42),
  nom_region  VARCHAR(42)
);

CREATE TABLE Permission (
  PRIMARY KEY (id_permission),
  id_permission  INT NOT NULL AUTO_INCREMENT,
  nom_permission VARCHAR(42)
);

CREATE TABLE Role (
  PRIMARY KEY (id_role),
  id_role  INT NOT NULL AUTO_INCREMENT,
  nom_role VARCHAR(42)
);

CREATE TABLE role_permission (
  PRIMARY KEY (id_role, id_permission),
  id_role       INT NOT NULL,
  id_permission INT NOT NULL
);

CREATE TABLE role_utilisateur (
  PRIMARY KEY (id_utilisateur, id_role),
  id_utilisateur INT NOT NULL,
  id_role        INT NOT NULL
);

CREATE TABLE Utilisateur (
  PRIMARY KEY (id_utilisateur),
  id_utilisateur INT NOT NULL AUTO_INCREMENT,
  pseudo         VARCHAR(42),
  hashcode       VARCHAR(42)
);

ALTER TABLE Image ADD FOREIGN KEY (nom_commune) REFERENCES Lieu (nom_commune);
ALTER TABLE Image ADD FOREIGN KEY (id_utilisateur) REFERENCES Utilisateur (id_utilisateur);

ALTER TABLE role_permission ADD FOREIGN KEY (id_permission) REFERENCES Permission (id_permission);
ALTER TABLE role_permission ADD FOREIGN KEY (id_role) REFERENCES Role (id_role);

ALTER TABLE role_utilisateur ADD FOREIGN KEY (id_role) REFERENCES Role (id_role);
ALTER TABLE role_utilisateur ADD FOREIGN KEY (id_utilisateur) REFERENCES Utilisateur (id_utilisateur);

-- Insertion
INSERT INTO `Role` (`id_role`, `nom_role`) VALUES 
(1, 'Administrateur'), 
(2, 'Contributeur'), 
(3, 'Joueur');

INSERT INTO `Permission` (`id_permission`, `nom_permission`) VALUES 
(1, 'accepter_puzzle'), 
(2, 'envoyer_puzzle');

INSERT INTO `role_permission` (`id_role`, `id_permission`) VALUES 
(1, 1),
(1, 2),
(2, 2);




