DROP DATABASE puzzle_db;
CREATE DATABASE puzzle_db;
\c puzzle_db;

-- Generated by Mocodo 4.3.2

CREATE TABLE Image (
  PRIMARY KEY (id_image),
  id_image       INT NOT NULL GENERATED ALWAYS AS IDENTITY,
  nom_image      VARCHAR(42),
  url            VARCHAR(100),
  id_utilisateur INT NULL,
  nom_monument   VARCHAR(100) NULL,
  description    VARCHAR(100) NULL,
  nom_commune    VARCHAR(42) NULL,
  geoloc         VARCHAR(42) NULL
);

CREATE TABLE Lieu (
  PRIMARY KEY (nom_commune),
  nom_commune VARCHAR(42) NOT NULL,
  code_dept   VARCHAR(3),
  nom_dept    VARCHAR(42),
  nom_region  VARCHAR(42)
);

CREATE TABLE Permission (
  PRIMARY KEY (id_permission),
  id_permission  INT NOT NULL GENERATED ALWAYS AS IDENTITY,
  nom_permission VARCHAR(42)
);

CREATE TABLE Role (
  PRIMARY KEY (id_role),
  id_role  INT NOT NULL GENERATED ALWAYS AS IDENTITY,
  nom_role VARCHAR(42)
);

CREATE TABLE role_permission (
  PRIMARY KEY (id_role, id_permission),
  id_role       INT NOT NULL,
  id_permission INT NOT NULL
);

CREATE TABLE role_utilisateur (
  PRIMARY KEY (id_utilisateur, id_role),
  id_utilisateur INT NOT NULL,
  id_role        INT NOT NULL
);

CREATE TABLE Utilisateur (
  PRIMARY KEY (id_utilisateur),
  id_utilisateur INT NOT NULL GENERATED ALWAYS AS IDENTITY,
  pseudo         VARCHAR(42),
  hashcode       VARCHAR(42)
);

ALTER TABLE Image ADD FOREIGN KEY (nom_commune) REFERENCES Lieu (nom_commune);
ALTER TABLE Image ADD FOREIGN KEY (id_utilisateur) REFERENCES Utilisateur (id_utilisateur);

ALTER TABLE role_permission ADD FOREIGN KEY (id_permission) REFERENCES Permission (id_permission);
ALTER TABLE role_permission ADD FOREIGN KEY (id_role) REFERENCES Role (id_role);

ALTER TABLE role_utilisateur ADD FOREIGN KEY (id_role) REFERENCES Role (id_role);
ALTER TABLE role_utilisateur ADD FOREIGN KEY (id_utilisateur) REFERENCES Utilisateur (id_utilisateur);

-- Insertion
INSERT INTO Role ("nom_role") VALUES 
('Administrateur'), 
('Contributeur'), 
('Joueur');

INSERT INTO Permission ("nom_permission") VALUES 
('accepter_puzzle'), 
('envoyer_puzzle');

INSERT INTO role_permission ("id_role", "id_permission") VALUES 
(1, 1),
(1, 2),
(2, 2);




